* This will show you how to handle incoming and outgoing calls.
  In a simple web app using your twilio account.
  https://www.twilio.com/docs/quickstart/ruby/twiml
* Incoming calls.
  The simplest way to handle an incoming call.
  Just say "Hello Monkey" when someone makes a call to
  your Twilio number
** See twiml-quickstart.rb for details.
** Run the Sintra app to listen for incoming calls.
   $ bundle exec ruby twiml-quickstart.rb
** Make the app accessable from outside your internal network/router
   $ ngrok http 4567
** Setup you're Twilio number to forward calls to this web app.
*** Go to your Twilio account console
    https://www.twilio.com/console
*** Select "# Phone Numbers"
    https://www.twilio.com/console/phone-numbers/incoming
*** Select one of your Twilio phone nubers.
    +1 978-291-7627
    https://www.twilio.com/console/phone-numbers/PNe35730997bfaec8441f3363f0c7b20df
*** Select the Configure Tab, if it's not already selected.
*** In the Voice & Fax Section
    In the "A CALL COMES IN" textbox.
    ENTER the below URL, /hello-monkey with the domain name provided by ngrok above.
    Ex: https://9e118b7d.ngrok.io/hello-monkey
    Select GET from the drop-down to the right of this text box.
    SAVE (Don't forget to hit the save button!!!!)
** Make an incoming call to your app.
   From a phone call 978 291-7626

   You'll hear a message to upgrade your account then a prompt to select any number.
** The Twilio server will see a HTTP GET request to /hello-monkey
   This request will contain a lot of info about the caller and who they are trying to reach.
   34.207.245.21 - - [19/Jun/2017:11:58:30 -0400] "GET /hello-monkey?Called=%2B19782917627&ToState=MA&CallerCountry=US&Direction=inbound&CallerState=MA&ToZip=01843&CallSid=CA861c0302f5f6f90df446586bdb06c904&To=%2B19782917627&CallerZip=01970&ToCountry=US&ApiVersion=2010-04-01&CalledZip=01843&CalledCity=LAWRENCE&CallStatus=ringing&From=%2B19789853901&AccountSid=AC499544b4f8fea886d0e1d219487fa9f2&CalledCountry=US&CallerCity=LAWRENCE&Caller=%2B19789853901&FromCountry=US&ToCity=LAWRENCE&FromCity=LAWRENCE&CalledState=MA&FromZip=01970&FromState=MA HTTP/1.1" 200 84 0.0073
*** To=%2B19782917627
    This is the number being called. +19782917627
*** From=%2B19789853901
    +19789853901
** Identify incoming callers.
   twiml-quickstart_greet_callers.rb
   Calling 978 291-7626
   From my phone will say "Hello Tom Dyer"
** Connect incoming caller to another phone number.
   $ bundle exec ruby twiml-quickstart_greet_callers.rb

   https://www.twilio.com/docs/quickstart/ruby/twiml/connect-call-to-second-person

*** This will wait for an incoming call from Twilio to the /hello-monkey URL
*** Then will say "Hello Tom Dyer"
*** Then play the monkey.mp3
*** Then ask user to to press 1.
*** Then say press any key to start over.
*** Then Gather the digits the incoming caller selected.
    The incoming caller can select these digits before the message is finished.
*** If the incoming caller selects '1' then the Twilio will fire a
    HTTP GET /hello-monkey/handle-gather which will
**** Dial Koko's phone number
    r.Dial '+13105551212' ### Connect the caller to Koko, or your cell
**** This doesn't seem to work????
* Making an Outgoing call.
